---
version: "3.3"
services:
  scemo-pezzente-api-1:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: scemo-pezzente-api-1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "scemo-pezzente-api:latest"
    restart: "no"
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    entrypoint: ./entrypoint.sh
    networks:
      - caching
  scemo-pezzente-api-2:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: scemo-pezzente-api-2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "scemo-pezzente-api:latest"
    restart: "no"
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    entrypoint: uwsgi --ini uwsgi.ini --enable-threads --socket /tmp/scemo-pezzente-api/scemo-pezzente-2.sock
    networks:
      - caching
  battuteapi:
    build:
      context: ./battuteAPI
      dockerfile: Dockerfile
    container_name: battuteapi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "battuteapi:latest"
    volumes:
      - ./config/battuteapi_data:/usr/src/app/data
    ports:
      - 3050:3050
  redis:
    image: redis
    container_name: voicebot-redis
    networks:
      - caching
  scemo-pezzente-api-balancer:
    build:
      context: ./api
      dockerfile: Dockerfile.balancer
    container_name: scemo-pezzente-api-balancer
    image: "scemo-pezzente-api-balancer:latest"
    ports:
      - "5080:80"
    depends_on:
      - scemo-pezzente-api-1
      - scemo-pezzente-api-2
      - scemo-pezzente-api-3
      - scemo-pezzente-api-4
    volumes:
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"